global using Serilog;
global using CleanArchitecture.DDD.API.ExtensionMethods;
global using CleanArchitecture.DDD.Core;
global using CleanArchitecture.DDD.Domain.ValueObjects;
global using CleanArchitecture.DDD.Infrastructure.Persistence.DbContext;
global using FluentValidation;
global using FluentValidation.AspNetCore;
global using Microsoft.EntityFrameworkCore;
global using MediatR;