// <auto-generated />
using System;
using CleanArchitecture.DDD.Infrastructure.Persistence.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleanArchitecture.DDD.Infrastructure.Migrations
{
    [DbContext(typeof(DomainDbContext))]
    [Migration("20230416102334_Added-Patient-Table")]
    partial class AddedPatientTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.2.23128.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CleanArchitecture.DDD.Infrastructure.Persistence.Entities.Address", b =>
                {
                    b.Property<Guid>("AddressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SoftDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressID");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            AddressID = new Guid("b70ef8e1-0470-4fc4-a979-03a5b8d51dea"),
                            City = "Alt Julika",
                            Country = "Schweiz",
                            SoftDeleted = false,
                            StreetAddress = "Lerchengasse",
                            ZipCode = "71570"
                        },
                        new
                        {
                            AddressID = new Guid("293b80b5-b6a7-41ae-b9f4-0e5c76b2de91"),
                            City = "Kimscheid",
                            Country = "Deutschland",
                            SoftDeleted = false,
                            StreetAddress = "Auf der Ohmer",
                            ZipCode = "59891"
                        },
                        new
                        {
                            AddressID = new Guid("c0ef290a-ec8d-4757-ac1b-5841fdc93ed8"),
                            City = "Ost Christian",
                            Country = "Deutschland",
                            SoftDeleted = false,
                            StreetAddress = "Steinbücheler Feld",
                            ZipCode = "29349"
                        },
                        new
                        {
                            AddressID = new Guid("01ad1157-e814-4a3e-967a-175dc6547391"),
                            City = "Bad Lukasland",
                            Country = "Deutschland",
                            SoftDeleted = false,
                            StreetAddress = "Martin-Luther-Str.",
                            ZipCode = "57433"
                        },
                        new
                        {
                            AddressID = new Guid("1cde8477-9470-4efa-b36d-54b24ebe9a78"),
                            City = "Neu Hailey",
                            Country = "Deutschland",
                            SoftDeleted = false,
                            StreetAddress = "Bergstr.",
                            ZipCode = "13775"
                        },
                        new
                        {
                            AddressID = new Guid("b77d3a11-be7d-4f1b-a8ed-28df83185680"),
                            City = "Nord Lenny",
                            Country = "Osterreich",
                            SoftDeleted = false,
                            StreetAddress = "Lötzener Str.",
                            ZipCode = "06522"
                        },
                        new
                        {
                            AddressID = new Guid("3824358b-e3a6-43d4-9e16-a4a138027bcc"),
                            City = "Erwesstadt",
                            Country = "Osterreich",
                            SoftDeleted = false,
                            StreetAddress = "Quarzstr.",
                            ZipCode = "06845"
                        },
                        new
                        {
                            AddressID = new Guid("05e57f0c-d1cb-47ac-b6ad-f7879baa7e37"),
                            City = "Obermaierscheid",
                            Country = "Schweiz",
                            SoftDeleted = false,
                            StreetAddress = "Am Nonnenbruch",
                            ZipCode = "24426"
                        },
                        new
                        {
                            AddressID = new Guid("023464bc-b29d-4a19-b7e1-96c59fa17d30"),
                            City = "West Carolin",
                            Country = "Osterreich",
                            SoftDeleted = false,
                            StreetAddress = "Schlehdornstr.",
                            ZipCode = "62762"
                        },
                        new
                        {
                            AddressID = new Guid("fbb8bc2f-d65d-4d00-a4d7-4dea279882e0"),
                            City = "Buderburg",
                            Country = "Osterreich",
                            SoftDeleted = false,
                            StreetAddress = "Bruchhauser Str.",
                            ZipCode = "10246"
                        },
                        new
                        {
                            AddressID = new Guid("9b567c54-d378-4a58-b5e7-af76c507da58"),
                            City = "Bad Tamialand",
                            Country = "Deutschland",
                            SoftDeleted = false,
                            StreetAddress = "Im Eisholz",
                            ZipCode = "75992"
                        },
                        new
                        {
                            AddressID = new Guid("016396c9-9f65-40c3-b7ec-2c457beb6bb0"),
                            City = "Alt Markdorf",
                            Country = "Deutschland",
                            SoftDeleted = false,
                            StreetAddress = "Grünstr.",
                            ZipCode = "30833"
                        },
                        new
                        {
                            AddressID = new Guid("f7838350-c389-493f-8b74-632f20b39b62"),
                            City = "Albertscheid",
                            Country = "Deutschland",
                            SoftDeleted = false,
                            StreetAddress = "Am Kühnsbusch",
                            ZipCode = "18163"
                        },
                        new
                        {
                            AddressID = new Guid("397f954f-af81-4b53-af18-997cc56eb08e"),
                            City = "Ost Merveburg",
                            Country = "Osterreich",
                            SoftDeleted = false,
                            StreetAddress = "Hitdorfer Kirchweg",
                            ZipCode = "59670"
                        },
                        new
                        {
                            AddressID = new Guid("b434a206-d5b0-46bd-b8d1-caab32c54e7c"),
                            City = "Majaburg",
                            Country = "Schweiz",
                            SoftDeleted = false,
                            StreetAddress = "Oskar-Moll-Str.",
                            ZipCode = "16740"
                        },
                        new
                        {
                            AddressID = new Guid("4f19e7f0-01df-4708-8f5f-34b68e6fa4e4"),
                            City = "Mortendorf",
                            Country = "Osterreich",
                            SoftDeleted = false,
                            StreetAddress = "Willy-Brandt-Ring",
                            ZipCode = "95355"
                        },
                        new
                        {
                            AddressID = new Guid("1e96ec6a-5941-4397-989f-c37dabb574fd"),
                            City = "Süd Benjaminscheid",
                            Country = "Schweiz",
                            SoftDeleted = false,
                            StreetAddress = "Unter dem Schildchen",
                            ZipCode = "32205"
                        },
                        new
                        {
                            AddressID = new Guid("6e4086e9-63bb-4248-ac83-a327d3c0b1de"),
                            City = "Ost Marlene",
                            Country = "Deutschland",
                            SoftDeleted = false,
                            StreetAddress = "Wiembachallee",
                            ZipCode = "50047"
                        },
                        new
                        {
                            AddressID = new Guid("19db99b7-50cd-4d29-bc9d-05c1bf240a59"),
                            City = "Bad Nielsland",
                            Country = "Schweiz",
                            SoftDeleted = false,
                            StreetAddress = "Feuerdornweg",
                            ZipCode = "19394"
                        },
                        new
                        {
                            AddressID = new Guid("661b25cb-d993-43c0-aea3-ad402ad8cdc4"),
                            City = "Ost Oscarland",
                            Country = "Schweiz",
                            SoftDeleted = false,
                            StreetAddress = "Am Hühnerberg",
                            ZipCode = "19819"
                        },
                        new
                        {
                            AddressID = new Guid("f85a3a34-9322-4ba2-962c-efb6219fc138"),
                            City = "Neu Toni",
                            Country = "Deutschland",
                            SoftDeleted = false,
                            StreetAddress = "Am Heidkamp",
                            ZipCode = "36273"
                        },
                        new
                        {
                            AddressID = new Guid("1d33fcc5-427d-4a46-b4af-d2da015e96fc"),
                            City = "Mullerstadt",
                            Country = "Osterreich",
                            SoftDeleted = false,
                            StreetAddress = "Carl-Rumpff-Str.",
                            ZipCode = "98311"
                        },
                        new
                        {
                            AddressID = new Guid("6536258b-294c-4101-b39a-f9f438ba916b"),
                            City = "Ost Ashley",
                            Country = "Osterreich",
                            SoftDeleted = false,
                            StreetAddress = "Am Scherfenbrand",
                            ZipCode = "13238"
                        },
                        new
                        {
                            AddressID = new Guid("3ac75e17-5a9b-44e5-99b9-39667cceaefc"),
                            City = "Weimerland",
                            Country = "Deutschland",
                            SoftDeleted = false,
                            StreetAddress = "Nauener Str.",
                            ZipCode = "80624"
                        },
                        new
                        {
                            AddressID = new Guid("d4161cba-9f34-4de4-b6a3-393a8f98a0c4"),
                            City = "Seilerdorf",
                            Country = "Osterreich",
                            SoftDeleted = false,
                            StreetAddress = "Im Kalkfeld",
                            ZipCode = "80073"
                        },
                        new
                        {
                            AddressID = new Guid("85761bcb-c169-43b1-9d92-675d585821d2"),
                            City = "Nord Jasmine",
                            Country = "Osterreich",
                            SoftDeleted = false,
                            StreetAddress = "Küppersteger Str.",
                            ZipCode = "55149"
                        },
                        new
                        {
                            AddressID = new Guid("f0464e55-ba30-40ee-b8d1-3bac4217ec6e"),
                            City = "Neu Milo",
                            Country = "Deutschland",
                            SoftDeleted = false,
                            StreetAddress = "Am Sportplatz",
                            ZipCode = "78854"
                        },
                        new
                        {
                            AddressID = new Guid("501d72f7-e291-4ab1-993b-e2b4b4fdfffd"),
                            City = "Alt Julianeburg",
                            Country = "Schweiz",
                            SoftDeleted = false,
                            StreetAddress = "Wilhelmsgasse",
                            ZipCode = "94769"
                        },
                        new
                        {
                            AddressID = new Guid("5eb1db1e-ed38-4cc4-b7b7-6f823171e173"),
                            City = "Neu Riccardo",
                            Country = "Osterreich",
                            SoftDeleted = false,
                            StreetAddress = "Am Thelenhof",
                            ZipCode = "45206"
                        },
                        new
                        {
                            AddressID = new Guid("5333e837-63d1-4e61-a13f-dd90b943863e"),
                            City = "Süd Isabel",
                            Country = "Osterreich",
                            SoftDeleted = false,
                            StreetAddress = "Pfeilshofstr.",
                            ZipCode = "81522"
                        },
                        new
                        {
                            AddressID = new Guid("02b5340b-f8a4-4572-8577-f28b209480a9"),
                            City = "Krauseburg",
                            Country = "Schweiz",
                            SoftDeleted = false,
                            StreetAddress = "Friedlieb-Ferdinand-Runge-Str.",
                            ZipCode = "88436"
                        },
                        new
                        {
                            AddressID = new Guid("edfcff51-b74a-4304-82dd-463da8e029bc"),
                            City = "Janderscheid",
                            Country = "Osterreich",
                            SoftDeleted = false,
                            StreetAddress = "Ewald-Röll-Str.",
                            ZipCode = "66074"
                        },
                        new
                        {
                            AddressID = new Guid("46eece4d-7027-48ca-9ca2-7255ea8005b6"),
                            City = "Schottstadt",
                            Country = "Deutschland",
                            SoftDeleted = false,
                            StreetAddress = "Bürriger Weg",
                            ZipCode = "22375"
                        },
                        new
                        {
                            AddressID = new Guid("ebfb43b2-3a4a-4e4b-aa09-2ef2214a2323"),
                            City = "Kaidorf",
                            Country = "Deutschland",
                            SoftDeleted = false,
                            StreetAddress = "Ulrich-von-Hassell-Str.",
                            ZipCode = "70577"
                        },
                        new
                        {
                            AddressID = new Guid("9aa14864-8383-4e04-90c9-9c3a34ea3c1d"),
                            City = "Neu Gerrit",
                            Country = "Osterreich",
                            SoftDeleted = false,
                            StreetAddress = "Auf der Grieße",
                            ZipCode = "72167"
                        },
                        new
                        {
                            AddressID = new Guid("ce5c3fee-db17-4690-96fe-bdd8f455d139"),
                            City = "West Raphaelburg",
                            Country = "Schweiz",
                            SoftDeleted = false,
                            StreetAddress = "Pescher Busch",
                            ZipCode = "79391"
                        },
                        new
                        {
                            AddressID = new Guid("c06a3fda-256d-4a76-a617-63d2a3e8dca2"),
                            City = "Kruschinskiburg",
                            Country = "Osterreich",
                            SoftDeleted = false,
                            StreetAddress = "Bonifatiusstr.",
                            ZipCode = "73278"
                        },
                        new
                        {
                            AddressID = new Guid("f836be9b-a9bc-4331-a101-af5daace4acd"),
                            City = "Juliestadt",
                            Country = "Schweiz",
                            SoftDeleted = false,
                            StreetAddress = "Rotdornweg",
                            ZipCode = "58731"
                        },
                        new
                        {
                            AddressID = new Guid("1cac9171-f001-43ff-bed5-e07c5220aa37"),
                            City = "Michallekdorf",
                            Country = "Deutschland",
                            SoftDeleted = false,
                            StreetAddress = "Kyllstr.",
                            ZipCode = "76209"
                        },
                        new
                        {
                            AddressID = new Guid("aacd9c10-901f-4f30-992d-8673c51f4518"),
                            City = "Nord Kimberlyland",
                            Country = "Deutschland",
                            SoftDeleted = false,
                            StreetAddress = "Rheinallee",
                            ZipCode = "96659"
                        },
                        new
                        {
                            AddressID = new Guid("7693b453-7f93-4632-bc76-131c784e605a"),
                            City = "Ost Linnea",
                            Country = "Osterreich",
                            SoftDeleted = false,
                            StreetAddress = "Weiherfeld",
                            ZipCode = "10616"
                        },
                        new
                        {
                            AddressID = new Guid("35ae2c93-0f3d-4857-b22e-dd1efca4fc0d"),
                            City = "Florascheid",
                            Country = "Schweiz",
                            SoftDeleted = false,
                            StreetAddress = "Ginsterweg",
                            ZipCode = "69443"
                        },
                        new
                        {
                            AddressID = new Guid("00dbe4a4-3951-4699-a46b-8acde08f0a38"),
                            City = "Jamrozyscheid",
                            Country = "Schweiz",
                            SoftDeleted = false,
                            StreetAddress = "Lohrbergstr.",
                            ZipCode = "67147"
                        },
                        new
                        {
                            AddressID = new Guid("40fa84d2-b15e-4115-a9ef-917934b48a49"),
                            City = "Alt Thore",
                            Country = "Deutschland",
                            SoftDeleted = false,
                            StreetAddress = "Heimstättenweg",
                            ZipCode = "11439"
                        },
                        new
                        {
                            AddressID = new Guid("28354db4-2dfe-433c-ac52-e4b3a6ced106"),
                            City = "Süd Thiesstadt",
                            Country = "Osterreich",
                            SoftDeleted = false,
                            StreetAddress = "Ruhlachstr.",
                            ZipCode = "11097"
                        },
                        new
                        {
                            AddressID = new Guid("0149710f-f951-4f1d-ace2-e3a399fa602e"),
                            City = "Ost Sammy",
                            Country = "Osterreich",
                            SoftDeleted = false,
                            StreetAddress = "Kinderhausen",
                            ZipCode = "88181"
                        },
                        new
                        {
                            AddressID = new Guid("9dd65635-015a-4a57-ad4a-85e6d36de9e9"),
                            City = "Torbenstadt",
                            Country = "Osterreich",
                            SoftDeleted = false,
                            StreetAddress = "Marie-Curie-Str.",
                            ZipCode = "58601"
                        },
                        new
                        {
                            AddressID = new Guid("2672623a-26ac-41ae-8ff4-11a1d553d924"),
                            City = "Süd Christianstadt",
                            Country = "Schweiz",
                            SoftDeleted = false,
                            StreetAddress = "Feuerbachstr.",
                            ZipCode = "49666"
                        },
                        new
                        {
                            AddressID = new Guid("b414749b-87bf-4b57-8511-bacb35e53bc1"),
                            City = "Nord Jannestadt",
                            Country = "Schweiz",
                            SoftDeleted = false,
                            StreetAddress = "Raushofstr.",
                            ZipCode = "04314"
                        },
                        new
                        {
                            AddressID = new Guid("f669afea-dcd1-4f23-a728-e31bd508c1e4"),
                            City = "Kreissigstadt",
                            Country = "Osterreich",
                            SoftDeleted = false,
                            StreetAddress = "Burscheider Str.",
                            ZipCode = "91824"
                        },
                        new
                        {
                            AddressID = new Guid("5de7963b-5a45-4c59-b0d6-1376e2f11f25"),
                            City = "Jorisburg",
                            Country = "Schweiz",
                            SoftDeleted = false,
                            StreetAddress = "Carl-Leverkus-Str.",
                            ZipCode = "14683"
                        },
                        new
                        {
                            AddressID = new Guid("8a9ede42-2e69-4c19-8e2b-1044b0ed9850"),
                            City = "Bad Rianaburg",
                            Country = "Deutschland",
                            SoftDeleted = false,
                            StreetAddress = "Eintrachtstr.",
                            ZipCode = "10151"
                        },
                        new
                        {
                            AddressID = new Guid("286124e3-efd3-4ffb-b636-fdce91c08ae7"),
                            City = "Salowstadt",
                            Country = "Deutschland",
                            SoftDeleted = false,
                            StreetAddress = "Wilhelm-Busch-Str.",
                            ZipCode = "59018"
                        },
                        new
                        {
                            AddressID = new Guid("59da2cee-5036-4dc9-a337-2b2f62f7d7fb"),
                            City = "Paulineland",
                            Country = "Deutschland",
                            SoftDeleted = false,
                            StreetAddress = "Neuenkamp",
                            ZipCode = "12093"
                        },
                        new
                        {
                            AddressID = new Guid("08eb0b99-4819-4430-8fae-0ee78d653952"),
                            City = "Zehrascheid",
                            Country = "Schweiz",
                            SoftDeleted = false,
                            StreetAddress = "Linienstr.",
                            ZipCode = "51980"
                        },
                        new
                        {
                            AddressID = new Guid("c4479ffd-d261-42e6-9edc-34cc175966f2"),
                            City = "Alt Laurensburg",
                            Country = "Schweiz",
                            SoftDeleted = false,
                            StreetAddress = "Alte Landstr.",
                            ZipCode = "82551"
                        },
                        new
                        {
                            AddressID = new Guid("d7e38809-08c3-4833-a13b-c4ac58a2ad73"),
                            City = "Spiegelburgland",
                            Country = "Schweiz",
                            SoftDeleted = false,
                            StreetAddress = "Gellertstr.",
                            ZipCode = "94960"
                        },
                        new
                        {
                            AddressID = new Guid("550240a3-b5f9-470c-abdb-00e66a38d560"),
                            City = "Neu Leon",
                            Country = "Osterreich",
                            SoftDeleted = false,
                            StreetAddress = "Opladener Platz",
                            ZipCode = "87973"
                        },
                        new
                        {
                            AddressID = new Guid("80d0f792-4bbf-4c2e-bca2-7ced4b95f5b9"),
                            City = "Nord Allegra",
                            Country = "Osterreich",
                            SoftDeleted = false,
                            StreetAddress = "Sonderburger Str.",
                            ZipCode = "34238"
                        },
                        new
                        {
                            AddressID = new Guid("227a4782-3d98-4d58-a94e-b3b0d76f5f84"),
                            City = "Floredorf",
                            Country = "Osterreich",
                            SoftDeleted = false,
                            StreetAddress = "Am Plattenbusch",
                            ZipCode = "78155"
                        },
                        new
                        {
                            AddressID = new Guid("a35512de-142d-40c9-b849-d7df895dd01e"),
                            City = "Waschbüschdorf",
                            Country = "Schweiz",
                            SoftDeleted = false,
                            StreetAddress = "Saarstr.",
                            ZipCode = "71184"
                        },
                        new
                        {
                            AddressID = new Guid("b3bfa100-c430-4626-b412-5c191c86a616"),
                            City = "Bad Jano",
                            Country = "Deutschland",
                            SoftDeleted = false,
                            StreetAddress = "Albert-Zarthe-Weg",
                            ZipCode = "22604"
                        },
                        new
                        {
                            AddressID = new Guid("189aa5f2-fa09-417e-86cd-ba39a2ae5fb0"),
                            City = "Neu Mariam",
                            Country = "Schweiz",
                            SoftDeleted = false,
                            StreetAddress = "Dönhoffstr.",
                            ZipCode = "50251"
                        },
                        new
                        {
                            AddressID = new Guid("2d9849e2-5b43-4a84-9163-3be159e1ef95"),
                            City = "Bad Jellaland",
                            Country = "Osterreich",
                            SoftDeleted = false,
                            StreetAddress = "Niederfeldstr.",
                            ZipCode = "75149"
                        },
                        new
                        {
                            AddressID = new Guid("6302e69c-399a-45c0-a4fe-522b629223e2"),
                            City = "Deanburg",
                            Country = "Schweiz",
                            SoftDeleted = false,
                            StreetAddress = "Grüner Weg",
                            ZipCode = "75903"
                        },
                        new
                        {
                            AddressID = new Guid("c5a53d4d-f80e-41b8-84e2-06054326ce85"),
                            City = "Schönfeldstadt",
                            Country = "Deutschland",
                            SoftDeleted = false,
                            StreetAddress = "Quettinger Str.",
                            ZipCode = "64319"
                        },
                        new
                        {
                            AddressID = new Guid("efbff0a9-6af6-4704-bb6e-5f55b9cbc384"),
                            City = "Hessekdorf",
                            Country = "Osterreich",
                            SoftDeleted = false,
                            StreetAddress = "Im Rosengarten",
                            ZipCode = "23454"
                        },
                        new
                        {
                            AddressID = new Guid("d1d20406-4d81-4f18-84a6-d8f87e4f21ee"),
                            City = "Nord Martin",
                            Country = "Osterreich",
                            SoftDeleted = false,
                            StreetAddress = "Hornpottweg",
                            ZipCode = "80752"
                        },
                        new
                        {
                            AddressID = new Guid("97584810-e6ca-4fa6-9cb2-b250c9afe466"),
                            City = "Bernerburg",
                            Country = "Deutschland",
                            SoftDeleted = false,
                            StreetAddress = "Mühlenweg",
                            ZipCode = "68739"
                        },
                        new
                        {
                            AddressID = new Guid("3a27397d-7f88-48f2-8596-204112f44b9b"),
                            City = "Neu Jesperburg",
                            Country = "Schweiz",
                            SoftDeleted = false,
                            StreetAddress = "Freudenthaler Weg",
                            ZipCode = "49848"
                        },
                        new
                        {
                            AddressID = new Guid("2a7a5d7c-7c81-4c78-bddf-ba9f085a50b4"),
                            City = "Neu Aliyadorf",
                            Country = "Deutschland",
                            SoftDeleted = false,
                            StreetAddress = "Am Weingarten",
                            ZipCode = "09192"
                        },
                        new
                        {
                            AddressID = new Guid("7a3baaf2-97f4-497e-9b49-ea3301e7ca7a"),
                            City = "Chantaldorf",
                            Country = "Deutschland",
                            SoftDeleted = false,
                            StreetAddress = "St. Ingberter Str.",
                            ZipCode = "65339"
                        },
                        new
                        {
                            AddressID = new Guid("d5cd5801-5e60-4659-9284-e0ffc8469ea7"),
                            City = "Nord Selina",
                            Country = "Deutschland",
                            SoftDeleted = false,
                            StreetAddress = "Sperberweg",
                            ZipCode = "11056"
                        },
                        new
                        {
                            AddressID = new Guid("b72d5c3c-8b3f-4a45-91b6-e4a557c644bd"),
                            City = "Maximastadt",
                            Country = "Schweiz",
                            SoftDeleted = false,
                            StreetAddress = "Samlandstr.",
                            ZipCode = "93946"
                        },
                        new
                        {
                            AddressID = new Guid("6ec61cd7-8bfe-447a-a06e-9aaaacabdd67"),
                            City = "Neu Emmydorf",
                            Country = "Osterreich",
                            SoftDeleted = false,
                            StreetAddress = "Kantstr.",
                            ZipCode = "28053"
                        },
                        new
                        {
                            AddressID = new Guid("4f38a541-78be-4692-afe2-2aa79b038d87"),
                            City = "Nord Caitlindorf",
                            Country = "Osterreich",
                            SoftDeleted = false,
                            StreetAddress = "An den Irlen",
                            ZipCode = "83572"
                        },
                        new
                        {
                            AddressID = new Guid("5288594f-f6a1-40f1-9536-7acaa976f86a"),
                            City = "Jacobstadt",
                            Country = "Osterreich",
                            SoftDeleted = false,
                            StreetAddress = "Am Köllerweg",
                            ZipCode = "60572"
                        },
                        new
                        {
                            AddressID = new Guid("50caad02-b9aa-45ed-b61d-7533a8b1bfd2"),
                            City = "Böhmdorf",
                            Country = "Osterreich",
                            SoftDeleted = false,
                            StreetAddress = "Grundermühle",
                            ZipCode = "53260"
                        },
                        new
                        {
                            AddressID = new Guid("a010d7fd-cda3-474f-9dde-421465280fa1"),
                            City = "Süd Maxim",
                            Country = "Deutschland",
                            SoftDeleted = false,
                            StreetAddress = "Im Steinfeld",
                            ZipCode = "72206"
                        },
                        new
                        {
                            AddressID = new Guid("8b77328a-7700-41f8-b4f3-1bdcc6650ac0"),
                            City = "Lindaburg",
                            Country = "Osterreich",
                            SoftDeleted = false,
                            StreetAddress = "Driescher Hecke",
                            ZipCode = "76633"
                        },
                        new
                        {
                            AddressID = new Guid("d911cb0d-9a3e-4295-a3e1-2c75c100384b"),
                            City = "Alt Janinaburg",
                            Country = "Deutschland",
                            SoftDeleted = false,
                            StreetAddress = "Holzer Wiesen",
                            ZipCode = "74289"
                        },
                        new
                        {
                            AddressID = new Guid("e09337cc-f58b-440e-b226-769155b96111"),
                            City = "Neu Keremstadt",
                            Country = "Osterreich",
                            SoftDeleted = false,
                            StreetAddress = "Karl-Marx-Str.",
                            ZipCode = "37074"
                        },
                        new
                        {
                            AddressID = new Guid("d3ce43b2-06f6-474e-8c99-5417bef150ac"),
                            City = "West Catrinburg",
                            Country = "Schweiz",
                            SoftDeleted = false,
                            StreetAddress = "Habichtgasse",
                            ZipCode = "05549"
                        },
                        new
                        {
                            AddressID = new Guid("be79b73e-ce76-4b67-a5db-60e956bf406a"),
                            City = "Melisstadt",
                            Country = "Deutschland",
                            SoftDeleted = false,
                            StreetAddress = "Schwarzastr.",
                            ZipCode = "92959"
                        },
                        new
                        {
                            AddressID = new Guid("6781a41d-8ef4-4bc8-b140-fbe3a564e07b"),
                            City = "Nord Linostadt",
                            Country = "Schweiz",
                            SoftDeleted = false,
                            StreetAddress = "Ottweilerstr.",
                            ZipCode = "61712"
                        },
                        new
                        {
                            AddressID = new Guid("918be368-428f-4d1a-ab0f-afa9277deb31"),
                            City = "Wujakland",
                            Country = "Osterreich",
                            SoftDeleted = false,
                            StreetAddress = "Am Stadtpark",
                            ZipCode = "76876"
                        },
                        new
                        {
                            AddressID = new Guid("4b534b8b-1ac6-430e-9aa6-70fb4937be8f"),
                            City = "Neu Leanndorf",
                            Country = "Osterreich",
                            SoftDeleted = false,
                            StreetAddress = "Röttgerweg",
                            ZipCode = "66402"
                        },
                        new
                        {
                            AddressID = new Guid("966ec860-4bed-4e92-881b-a77012808e71"),
                            City = "Jannekscheid",
                            Country = "Schweiz",
                            SoftDeleted = false,
                            StreetAddress = "Merziger Str.",
                            ZipCode = "88835"
                        },
                        new
                        {
                            AddressID = new Guid("138a3932-a114-48d9-9225-c1b0f51fba8a"),
                            City = "Alt Alfredburg",
                            Country = "Schweiz",
                            SoftDeleted = false,
                            StreetAddress = "Strombergstr.",
                            ZipCode = "88290"
                        },
                        new
                        {
                            AddressID = new Guid("f77fa7ec-e510-41f2-acf2-9d9b8733d7c0"),
                            City = "Süd Milaland",
                            Country = "Schweiz",
                            SoftDeleted = false,
                            StreetAddress = "Am Knechtsgraben",
                            ZipCode = "53932"
                        },
                        new
                        {
                            AddressID = new Guid("be50bc48-f496-4c6e-81e2-9508e901f6cd"),
                            City = "West Frankaland",
                            Country = "Schweiz",
                            SoftDeleted = false,
                            StreetAddress = "Humboldtstr.",
                            ZipCode = "88585"
                        },
                        new
                        {
                            AddressID = new Guid("4959d14d-fe40-471d-90d2-d61edb166793"),
                            City = "Süd Summer",
                            Country = "Deutschland",
                            SoftDeleted = false,
                            StreetAddress = "Auf der Ohmer",
                            ZipCode = "23067"
                        },
                        new
                        {
                            AddressID = new Guid("3e77dd42-76bf-46e6-a480-da84b523efd2"),
                            City = "Evaburg",
                            Country = "Deutschland",
                            SoftDeleted = false,
                            StreetAddress = "Friedhofstr.",
                            ZipCode = "17655"
                        },
                        new
                        {
                            AddressID = new Guid("8cd6c7f0-5d63-46e4-b5de-1a73045a37a6"),
                            City = "Neu Mayaland",
                            Country = "Deutschland",
                            SoftDeleted = false,
                            StreetAddress = "Sperberweg",
                            ZipCode = "31764"
                        },
                        new
                        {
                            AddressID = new Guid("f42d2a38-c93a-4565-8549-fe2f04193f38"),
                            City = "Hentschelscheid",
                            Country = "Schweiz",
                            SoftDeleted = false,
                            StreetAddress = "Halfenleimbach",
                            ZipCode = "49864"
                        },
                        new
                        {
                            AddressID = new Guid("0ce5fba0-0cf0-4eec-87d8-c10c4bc14eb5"),
                            City = "West Keno",
                            Country = "Osterreich",
                            SoftDeleted = false,
                            StreetAddress = "Tempelhofer Str.",
                            ZipCode = "76603"
                        },
                        new
                        {
                            AddressID = new Guid("7dacb2f6-6ce7-49e9-b06a-c78a24d21abf"),
                            City = "Bad Lydiascheid",
                            Country = "Osterreich",
                            SoftDeleted = false,
                            StreetAddress = "Halfenleimbach",
                            ZipCode = "44186"
                        },
                        new
                        {
                            AddressID = new Guid("73d15da9-b54a-484a-b840-28260662f564"),
                            City = "Bad Yarascheid",
                            Country = "Schweiz",
                            SoftDeleted = false,
                            StreetAddress = "Katzbachstr.",
                            ZipCode = "75876"
                        },
                        new
                        {
                            AddressID = new Guid("22906b97-a4cb-4824-9058-aaa22d182ff7"),
                            City = "Madetzkyland",
                            Country = "Schweiz",
                            SoftDeleted = false,
                            StreetAddress = "Taubenweg",
                            ZipCode = "65752"
                        },
                        new
                        {
                            AddressID = new Guid("d5f09faf-fdbb-446a-9620-540613d0dfbf"),
                            City = "Neu Melekdorf",
                            Country = "Deutschland",
                            SoftDeleted = false,
                            StreetAddress = "Bebelstr.",
                            ZipCode = "84775"
                        });
                });

            modelBuilder.Entity("CleanArchitecture.DDD.Infrastructure.Persistence.Entities.Doctor", b =>
                {
                    b.Property<Guid>("DoctorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EDCMExternalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"));

                    b.Property<bool>("SoftDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Unknown");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("DoctorID");

                    b.HasIndex("AddressId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("CleanArchitecture.DDD.Infrastructure.Persistence.Entities.Patient", b =>
                {
                    b.Property<Guid>("PatientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("PatientID");

                    b.ToTable("Patient");
                });

            modelBuilder.Entity("CleanArchitecture.DDD.Infrastructure.Persistence.Entities.Doctor", b =>
                {
                    b.HasOne("CleanArchitecture.DDD.Infrastructure.Persistence.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CleanArchitecture.DDD.Domain.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("DoctorID")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Firstname")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Lastname")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Middlename")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("DoctorID");

                            b1.ToTable("Doctors");

                            b1.WithOwner()
                                .HasForeignKey("DoctorID");
                        });

                    b.Navigation("Address");

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("CleanArchitecture.DDD.Infrastructure.Persistence.Entities.Patient", b =>
                {
                    b.OwnsOne("CleanArchitecture.DDD.Infrastructure.Persistence.JSONColumn.PatientMasterData", "MasterData", b1 =>
                        {
                            b1.Property<Guid>("PatientID")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("Active")
                                .HasColumnType("bit");

                            b1.Property<DateTime>("DateOfBirth")
                                .HasColumnType("datetime2");

                            b1.Property<string>("PrimaryDoctor")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PatientID");

                            b1.ToTable("Patient");

                            b1.ToJson("MasterData");

                            b1.WithOwner()
                                .HasForeignKey("PatientID");
                        });

                    b.Navigation("MasterData")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
